language: node_js
node_js:
  - "8"
  - "10"
  - "11"

stages:
    - validation

jobs:
    include:
        - stage: validation
          name: "Unit tests"
          script: "npm test"

        - stage: validation
          name: "Lint"
          script: "npm test"

        - stage: publish
          name: "documentation"
          script: "npm run doc"
          if branches:
              - master
